# Generated by Django 5.1.3 on 2025-01-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categories",
            new_name="category",
        ),
    ]
